[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

; Give more memory to the program to fit BLE + WiFi + OTA
board_build.partitions = min_spiffs.csv

; --- OTA CONFIGURATION ---
; upload_protocol = espota
; upload_port = odrive-node.local
